cart/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.cart_detail, name='cart_detail'),
    url(r'^add/(?P<product_id>\d+)/$',  views.cart_add, name='cart_add'),
    url(r'^remove/(?P<product_id>\d+)/$',views.cart_remove, name='cart_remove'),
]

orders/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
        url(r'^create/$', views.order_create, name='order_create'),
        url(r'^admin/order/(?P<order_id>\d+)/$', views.admin_order_detail, name='admin_order_detail'),
        url(r'^admin/order/(?P<order_id>\d+)/pdf/$',  views.admin_order_pdf, name='admin_order_pdf'),
]

sports/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.product_list, name='product_list'),
    url(r'^(?P<category_slug>[-\w]+)/$', views.product_list,name='product_list_by_category'),
    url(r'^(?P<id>\d+)/(?P<slug>[-\w]+)/$', views.product_detail,name='product_detail'),
]

team3project/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from sports.views import login_view, logout_view, register_view


urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^login/', login_view, name='login'),
    url(r'^logout/', logout_view, name='logout'),
    url(r'^register/', register_view, name='register'),
    
    # restore password urls
    url(r'^reset/password_reset/$', auth_views.password_reset, name='password_reset_1'),
    url(r'^password-reset/done/$',auth_views.password_reset_done, {'template_name': 'registration/password_reset_done.html'}, name='password_reset_done'),
    url(r'^password-reset/confirm/(?P<uidb64>[-\w]+)/(?P<token>[-\w]+)/$', auth_views.password_reset_confirm,
            {'template_name': 'registration/password_reset_confirm.html'}, name='password_reset_confirm'),
    url(r'^password-reset/complete/$',auth_views.password_reset_complete, {'template_name': 'registration/password_reset_complete.html'}, name='password_reset_complete'),
    
    
    
    url(r'^orders/', include('orders.urls', namespace='orders')),
    url(r'^cart/', include('cart.urls', namespace='cart')),
    url(r'^paypal/', include('paypal.standard.ipn.urls')),
    url(r'^payment/', include('payment.urls', namespace='payment')),
    url(r'^', include('sports.urls', namespace='sports')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/forms.py
from django import forms


PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]

class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(
                                choices=PRODUCT_QUANTITY_CHOICES,
                                coerce=int)
    update = forms.BooleanField(required=False,
                                initial=False,
                                widget=forms.HiddenInput)

cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from sports.models import Product
from sports.models import Category
from .cart import Cart
from .forms import CartAddProductForm


@require_POST
def cart_add(request, product_id):
    categories = Category.objects.all()
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product,
                 quantity=cd['quantity'],
                 update_quantity=cd['update'])
    return redirect('cart:cart_detail')


def cart_remove(request, product_id):
    categories = Category.objects.all()
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')


def cart_detail(request):
    categories = Category.objects.all()
    cart = Cart(request)
    for item in cart:
        item['update_quantity_form'] = CartAddProductForm(initial={'quantity': item['quantity'],
                          'update': True})
    return render(request, 'cart/detail.html', {'cart': cart,'categories': categories})

cart/templates/cart/detail.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <title>MAVStar Sporting Goods</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <link href="{% static "css/base.css" %}" rel="stylesheet">    
    <style>
    	#header {
			padding: 10px 100px;
			overflow: auto;	
			font-family: 'Ubuntu', sans-serif;
			font-size: 25px;
			font-color: #5499C7;
		}
		#header.logo {	
			margin-right: 10%;	
		}
        /* Remove the navbar's default margin-bottom and rounded borders */
        .navbar {
            margin-bottom: 0;
            border-radius: 0;
            background: #5499C7;
            font-color:: white;	
        }

        /* Set height of the grid so .sidenav scan be 100% (adjust as needed) */
        .row.content {
            height: 450px;
            color: white;	
        }

        /* Set gray background color and 100% height */
        .sidenav {
            padding-top: 20px;
            background-color: #f1f1f1;
            height: 100%;
            color: white;	
        }

        /* Set black background color, white text and some padding */
        footer {
            background-color: #555;
            color: white;
            padding: 15px;
        }

        /* On small screens, set height to 'auto' for sidenav and grid */
        @media screen and (max-width: 767px) {
            .sidenav {
                height: auto;
                padding: 15px;
                color: white;	
            }

            .row.content {
                height: auto;
                color: white;	
            }
        }
        body {
        	font-family: 'Ubuntu', sans-serif;
            
			color: #4b89b3;
        }
        .navbar-inverse .navbar-nav li a {
    		color: white;
		}
       
        
        
  </style>
</head>
<body id="app-layout">
<div id="header">
    <a href="/" class="logo"><img  height="70px" src={% static 'img/bg_icon.jpg'%}></a>
   <span > <a href="/" >MAVStar Sporting Goods</a></span>
  </div>
<nav class="navbar navbar-inverse">
    <div class="container-fluid">
        <div class="navbar-header">

            <!-- Collapsed Hamburger -->
            <button type="button" class="navbar-toggle" data-toggle="collapse"
                    data-target="#myNavbar">
                <span class="sr-only">Toggle Navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>

            <!-- Branding Image -->
           
        </div>
        <div class="collapse navbar-collapse" id="myNavbar">
        <ul class="nav navbar-nav">
		      <li >
		        <a href="{% url "sports:product_list" %}">All</a>
		      </li>
		      {% for c in categories %}
		        <li>
		          <a href="{{ c.get_absolute_url }}">{{ c.name }}</a>
		        </li>
		      {% endfor %}
    	</ul>
        <ul class="nav navbar-nav navbar-right">
             {% with total_items=cart|length %}
    			{% if cart|length > 0 %}
		             <li><a href="{% url "cart:cart_detail" %}">		       	 				
		      			<span>Cart: {{ total_items }} item{{ total_items|pluralize }},
		        				${{ cart.get_total_price }} </span>
		        		</a>
		      		 </li>
		      	{% else %}
      			<li><a href="{% url "cart:cart_detail" %}">		       	 				
		      			<span>Cart: {{ total_items }} item{{ total_items|pluralize }},
		        				${{ cart.get_total_price }} </span>
		        		</a>
		      		 </li>
    			{% endif %}
  			 {% endwith %}
                {% if user.is_authenticated %}
                            <li><a href="{% url 'logout' %}"><i class="fa fa-btn fa-sign-out"></i>Logout</a></li>
                {% else %}	
                            <li><a href="{% url 'login' %}"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
                            <li><a href="{% url 'register' %}"><span class="glyphicon glyphicon-log-in"></span> Register</a></li>
                        
                {% endif %}
            </ul>
        </div>
    </div>
</nav>
<div class="content container">
    <div class="row">
<div class="row">
    <h3 style="padding-left: 15Px">Shopping Cart Details</h3>
</div>
 <div>
     <table class="table table-striped table-bordered table-hover">
        <thead>
            <tr class="bg-info">
                <th>Image</th>
                <th>Product</th>
                <th>Quantity</th>
                <th>Remove</th>
                <th>Unit price</th>
                <th>Price</th>
            </tr>
        </thead>
        <tbody>
            {% for item in cart %}
        	  {% with product=item.product %}
                <tr>
		            <td>
		              <a href="{{ product.get_absolute_url }}">
		                <img style="height:50px;"  src="{% if product.image %}{{ product.image.url }}{% else %}{% static "img/no_image.png" %}{% endif %}">                    
		              </a>
		            </td>
		            <td>{{ product.name }}</td>
		            <td>
		            	<form action="{% url "cart:cart_add" product.id %}" method="post">
		    				{{ item.update_quantity_form.quantity }}
		    				{{ item.update_quantity_form.update }}
		    				<input type="submit" value="Update">
		    				{% csrf_token %}
		 			    </form>
		            </td>
		            <td><a href="{% url "cart:cart_remove" product.id %}">Remove</a></td>
		            <td class="num">${{ item.price }}</td>
		            <td class="num">${{ item.total_price }}</td>
          		</tr>
        {% endwith %}
      {% endfor %}
      <tr>
        <td style="align:right;" colspan="5"><h4>Total</h4></td>
        <td class="num"><h4>${{ cart.get_total_price }}</h4></td>
      </tr>
      </tbody>
      </table>
      </div>
  
  <div class="col-md-10 col-md-offset-9" >
    <a href="{% url "sports:product_list" %}" class="btn btn-default">Continue shopping</a>
    <a href="{% url "orders:order_create" %}" class="btn btn-primary">
  Checkout
</a>
</div>
 </div>
 </div>
</body>
</html>