cart/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.cart_detail, name='cart_detail'),
    url(r'^add/(?P<product_id>\d+)/$',  views.cart_add, name='cart_add'),
    url(r'^remove/(?P<product_id>\d+)/$',views.cart_remove, name='cart_remove'),
]

payment/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^process/$', views.payment_process, name='process'),
    url(r'^done/$', views.payment_done, name='done'),
    url(r'^canceled/$', views.payment_canceled, name='canceled'),
]

sports/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.product_list, name='product_list'),
    url(r'^(?P<category_slug>[-\w]+)/$', views.product_list,name='product_list_by_category'),
    url(r'^(?P<id>\d+)/(?P<slug>[-\w]+)/$', views.product_detail,name='product_detail'),
]

team3project/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from sports.views import login_view, logout_view, register_view


urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^login/', login_view, name='login'),
    url(r'^logout/', logout_view, name='logout'),
    url(r'^register/', register_view, name='register'),
    
    # restore password urls
    url(r'^reset/password_reset/$', auth_views.password_reset, name='password_reset_1'),
    url(r'^password-reset/done/$',auth_views.password_reset_done, {'template_name': 'registration/password_reset_done.html'}, name='password_reset_done'),
    url(r'^password-reset/confirm/(?P<uidb64>[-\w]+)/(?P<token>[-\w]+)/$', auth_views.password_reset_confirm,
            {'template_name': 'registration/password_reset_confirm.html'}, name='password_reset_confirm'),
    url(r'^password-reset/complete/$',auth_views.password_reset_complete, {'template_name': 'registration/password_reset_complete.html'}, name='password_reset_complete'),
    
    
    
    url(r'^orders/', include('orders.urls', namespace='orders')),
    url(r'^cart/', include('cart.urls', namespace='cart')),
    url(r'^paypal/', include('paypal.standard.ipn.urls')),
    url(r'^payment/', include('payment.urls', namespace='payment')),
    url(r'^', include('sports.urls', namespace='sports')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

payment/models.py
from django.db import models

# Create your models here.

payment/views.py
from django.shortcuts import render
from decimal import Decimal
from django.conf import settings
from django.core.urlresolvers import reverse
from django.shortcuts import render, get_object_or_404
from paypal.standard.forms import PayPalPaymentsForm
from orders.models import Order
from sports.models import Category
from django.views.decorators.csrf import csrf_exempt

def payment_process(request):
    order_id = request.session.get('order_id')
    order = get_object_or_404(Order, id=order_id)
    categories = Category.objects.all()
    host = request.get_host()

    paypal_dict = {
        'business': settings.PAYPAL_RECEIVER_EMAIL,
        'amount': '%.2f' % order.get_total_cost().quantize(
                                                  Decimal('.01')),
        'item_name': 'Order {}'.format(order.id),
        'invoice': str(order.id),
        'currency_code': 'USD',
        'notify_url': 'http://{}{}'.format(host,
                                           reverse('paypal-ipn')),
        'return_url': 'http://{}{}'.format(host,
                                         reverse('payment:done')),
        'cancel_return': 'http://{}{}'.format(host,
                                     reverse('payment:canceled')),
    }
    form = PayPalPaymentsForm(initial=paypal_dict)
    return render(request,
                  'payment/process.html', 
                  {'order': order, 'form':form,'categories': categories})

@csrf_exempt
def payment_done(request):
    return render(request, 'payment/done.html')

@csrf_exempt
def payment_canceled(request):
    return render(request, 'payment/canceled.html')

payment/templates/payment/canceled.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <title>MAVStar Sporting Goods</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    
    <style>
    	#header {
			padding: 10px 100px;
			overflow: auto;	
			font-family: 'Ubuntu', sans-serif;
			font-size: 25px;
			font-color: #5499C7;
		}
		#header.logo {	
			margin-right: 10%;	
		}
        /* Remove the navbar's default margin-bottom and rounded borders */
        .navbar {
            margin-bottom: 0;
            border-radius: 0;
            background: #5499C7;
            color: white;	
        }

        /* Set height of the grid so .sidenav scan be 100% (adjust as needed) */
        .row.content {
            height: 450px
            color: white;	
        }

        /* Set gray background color and 100% height */
        .sidenav {
            padding-top: 20px;
            background-color: #f1f1f1;
            height: 100%;
            color: white;	
        }

        /* Set black background color, white text and some padding */
        footer {
            background-color: #555;
            color: white;
            padding: 15px;
        }

        /* On small screens, set height to 'auto' for sidenav and grid */
        @media screen and (max-width: 767px) {
            .sidenav {
                height: auto;
                padding: 15px;
                color: white;	
            }

            .row.content {
                height: auto;
                color: white;	
            }
        }
        body {
        	font-family: 'Ubuntu', sans-serif;
            background: #EFEFEF url(../static/img/bg01.png) repeat;
			color: #4b89b3;
        }
         .navbar-inverse .navbar-nav li a {
    		color: white;
		}
        
  </style>
</head>
<body id="app-layout">
<div id="header">
    <a href="/" class="logo"><img  height="70px" src={% static 'img/bg_icon.jpg'%}></a>
   <span > <a href="/" >MAVStar Sporting Goods</a></span>
  </div>
<nav class="navbar navbar-inverse">
    <div class="container-fluid">
        <div class="navbar-header">

            <!-- Collapsed Hamburger -->
            <button type="button" class="navbar-toggle" data-toggle="collapse"
                    data-target="#myNavbar">
                <span class="sr-only">Toggle Navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>

            <!-- Branding Image -->
           
        </div>
        <div class="collapse navbar-collapse" id="myNavbar">
             <ul class="nav navbar-nav navbar-right">
                {% if user.is_authenticated %}
                            <li><a href="{% url 'logout' %}"><i class="fa fa-btn fa-sign-out"></i>Logout</a></li>
                {% else %}	
                            <li><a href="{% url 'login' %}"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
                            <li><a href="{% url 'register' %}"><span class="glyphicon glyphicon-log-in"></span> Register</a></li>
                        
                {% endif %}
            </ul>
        </div>
    </div>
</nav>

<div class='col-sm-8 col-sm-offset-3'>
  <h2>Your payment has not been processed</h2>
  <p>There was a problem processing your payment.</p>
</div>       
   
</body>
</html>

payment/templates/payment/done.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <title>MAVStar Sporting Goods</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    
    <style>
    	#header {
			padding: 10px 100px;
			overflow: auto;	
			font-family: 'Ubuntu', sans-serif;
			font-size: 25px;
			font-color: #5499C7;
		}
		#header.logo {	
			margin-right: 10%;	
		}
        /* Remove the navbar's default margin-bottom and rounded borders */
        .navbar {
            margin-bottom: 0;
            border-radius: 0;
            background: #5499C7;
            color: white;	
        }

        /* Set height of the grid so .sidenav scan be 100% (adjust as needed) */
        .row.content {
            height: 450px
            color: white;	
        }

        /* Set gray background color and 100% height */
        .sidenav {
            padding-top: 20px;
            background-color: #f1f1f1;
            height: 100%;
            color: white;	
        }

        /* Set black background color, white text and some padding */
        footer {
            background-color: #555;
            color: white;
            padding: 15px;
        }

        /* On small screens, set height to 'auto' for sidenav and grid */
        @media screen and (max-width: 767px) {
            .sidenav {
                height: auto;
                padding: 15px;
                color: white;	
            }

            .row.content {
                height: auto;
                color: white;	
            }
        }
        body {
        	font-family: 'Ubuntu', sans-serif;
            background: #EFEFEF url(../static/img/bg01.png) repeat;
			color: #4b89b3;
        }
         .navbar-inverse .navbar-nav li a {
    		color: white;
		}
        
  </style>
</head>
<body id="app-layout">
<div id="header">
    <a href="/" class="logo"><img  height="70px" src={% static 'img/bg_icon.jpg'%}></a>
   <span > <a href="/" >MAVStar Sporting Goods</a></span>
  </div>
<nav class="navbar navbar-inverse">
    <div class="container-fluid">
        <div class="navbar-header">

            <!-- Collapsed Hamburger -->
            <button type="button" class="navbar-toggle" data-toggle="collapse"
                    data-target="#myNavbar">
                <span class="sr-only">Toggle Navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>

            <!-- Branding Image -->
           
        </div>
        <div class="collapse navbar-collapse" id="myNavbar">
             <ul class="nav navbar-nav navbar-right">
                {% if user.is_authenticated %}
                            <li><a href="{% url 'logout' %}"><i class="fa fa-btn fa-sign-out"></i>Logout</a></li>
                {% else %}	
                            <li><a href="{% url 'login' %}"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
                            <li><a href="{% url 'register' %}"><span class="glyphicon glyphicon-log-in"></span> Register</a></li>
                        
                {% endif %}
            </ul>
        </div>
    </div>
</nav>

<div class='col-sm-8 col-sm-offset-3'>
  <h2>Your payment was successful</h2>
  <p>Your payment has been successfully received.</p>
</div>       
   
</body>
</html>

payment/templates/payment/process.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <title>MAVStar Sporting Goods</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <link href="{% static "css/base.css" %}" rel="stylesheet">
    <style>
    	#header {
			padding: 10px 100px;
			overflow: auto;	
			font-family: 'Ubuntu', sans-serif;
			font-size: 25px;
			font-color: #5499C7;
		}
		#header.logo {	
			margin-right: 10%;	
		}
        /* Remove the navbar's default margin-bottom and rounded borders */
        .navbar {
            margin-bottom: 0;
            border-radius: 0;
            background: #5499C7;
            color: white;	
        }

        /* Set height of the grid so .sidenav scan be 100% (adjust as needed) */
        .row.content {
            height: 450px
            color: white;	
        }

        /* Set gray background color and 100% height */
        .sidenav {
            padding-top: 20px;
            background-color: #f1f1f1;
            height: 100%;
            color: white;	
        }

        /* Set black background color, white text and some padding */
        footer {
            background-color: #555;
            color: white;
            padding: 15px;
        }

        /* On small screens, set height to 'auto' for sidenav and grid */
        @media screen and (max-width: 767px) {
            .sidenav {
                height: auto;
                padding: 15px;
                color: white;	
            }

            .row.content {
                height: auto;
                color: white;	
            }
        }
        body {
        	font-family: 'Ubuntu', sans-serif;
            background: #EFEFEF url(../static/img/bg01.png) repeat;
			color: #4b89b3;
        }
        .order-form {
			float: left;
		}
		
		.order-info {
			float: right;
			width: 300px;
			background: #efefef;
			padding: 10px 20px;
			color: #333;
			border-bottom: 4px solid #5993bb;
		}
		
		.order-info h3 {
			color: #5993bb;
		}
		
		.order-info ul li {
			margin: 0;
			padding: 0;
			font-size: 14px;
		}
		
		.order-info p {
			font-weight: bold;
			float: right;
		}
		
		.order-info span {
			float: right;
		}
		 .navbar-inverse .navbar-nav li a {
    		color: white;
		}
        
        
  </style>
</head>
<body id="app-layout">
<div id="header">
    <a href="/" class="logo"><img  height="70px" src={% static 'img/bg_icon.jpg'%}></a>
   <span > <a href="/" >MAVStar Sporting Goods</a></span>
  </div>
<nav class="navbar navbar-inverse">
    <div class="container-fluid">
        <div class="navbar-header">

            <!-- Collapsed Hamburger -->
            <button type="button" class="navbar-toggle" data-toggle="collapse"
                    data-target="#myNavbar">
                <span class="sr-only">Toggle Navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>

            <!-- Branding Image -->
           
        </div>
        <div class="collapse navbar-collapse" id="myNavbar">
        <ul class="nav navbar-nav">
		      <li >
		        <a href="{% url "sports:product_list" %}">All</a>
		      </li>
		      {% for c in categories %}
		        <li>
		          <a href="{{ c.get_absolute_url }}">{{ c.name }}</a>
		        </li>
		      {% endfor %}
    	</ul>
        <ul class="nav navbar-nav navbar-right">
             {% with total_items=cart|length %}
    			{% if cart|length > 0 %}
		             <li><a href="{% url "cart:cart_detail" %}">		       	 				
		      			<span>Cart: {{ total_items }} item{{ total_items|pluralize }},
		        				${{ cart.get_total_price }} </span>
		        		</a>
		      		 </li>
		      	{% else %}
      			<li><a href="{% url "cart:cart_detail" %}">		       	 				
		      			<span>Cart: {{ total_items }} item{{ total_items|pluralize }},
		        				${{ cart.get_total_price }} </span>
		        		</a>
		      		 </li>
    			{% endif %}
  			 {% endwith %}
                {% if user.is_authenticated %}
                            <li><a href="{% url 'logout' %}"><i class="fa fa-btn fa-sign-out"></i>Logout</a></li>
                {% else %}	
                            <li><a href="{% url 'login' %}"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
                            <li><a href="{% url 'register' %}"><span class="glyphicon glyphicon-log-in"></span> Register</a></li>
                        
                {% endif %}
            </ul>
        </div>
    </div>
</nav>

<div class='col-sm-8 col-sm-offset-2'>
 <h2>Pay using PayPal</h2>
                <div class="panel panel-primary">
                    {% if user.is_authenticated %}
                    	<div class="panel-heading">{{ user.username }} !</div>
                	{% else %}
                		<div class="panel-heading">Welcome!</div>
                	{% endif %}
                    <div class="panel-body">
                       {{ form.render }}
                    </div>
        </div>
</div>       
   
</body>
</html>